# Generated by Django 3.2.16 on 2022-11-06 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('janken_app', '0002_alter_janken_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='janken',
            old_name='win',
            new_name='win_count',
        ),
        migrations.AddField(
            model_name='janken',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
